export const jobList = [
    {
        index: 0,
        image: 'https://e7.pngegg.com/pngimages/225/716/png-clipart-computer-icons-computer-programming-logo-bing-search-engine-people-angle-text.png',
        profession: 'Técnico',
        subCategorias: ['Programador', 'Ingeniero'],
        empresa: 'Federico SAS',
        lugar: 'Bogotá',
        salario: '1.4M COP',
        vacantes: 2,
        publicacion: 'about 1 hour ago',
    },
    {
        index: 1,
        image: 'https://plus.unsplash.com/premium_photo-1669075651900-9eed0773e4c8?q=80&w=2080&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        profession: 'Diseñador Gráfico',
        subCategorias: ['Ilustrador', 'Animador'],
        empresa: 'Creativa Studio',
        lugar: 'Medellín',
        salario: '2.0M COP',
        vacantes: 1,
        publicacion: 'Yesterday',
    },
    {
        index: 2,
        image: 'https://www.vectorizando.com/wp-content/uploads/2021/05/Lenguaje-de-programacion-C-64ca4748.svg',
        profession: 'Diseñador Gráfico',
        subCategorias: ['Ilustrador', 'Animador'],
        empresa: 'Creativa Studio',
        lugar: 'Medellín',
        salario: '2.0M COP',
        vacantes: 1,
        publicacion: 'Yesterday',
    },
    {
        index: 3,
        image: 'https://plus.unsplash.com/premium_photo-1669075651900-9eed0773e4c8?q=80&w=2080&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        profession: 'Ingeniero de Software',
        subCategorias: ['Desarrollador Frontend', 'Desarrollador Backend'],
        empresa: 'Tech Innovators',
        lugar: 'Cali',
        salario: '2.5M COP',
        vacantes: 3,
        publicacion: '2 days ago',
    },
    {
        index: 4,
        image: 'https://lenguajesdeprogramacion.net/wp-content/uploads/2022/09/lenguajes-de-programacion-logo.png',
        profession: 'Ingeniero de Sistemas',
        subCategorias: ['Desarrollador Frontend', 'Desarrollador Backend'],
        empresa: 'Colombian Tech',
        lugar: 'Cali',
        salario: '3.5M COP',
        vacantes: 4,
        publicacion: '5 days ago',
    },
    {
        index: 5,
        image: 'https://lenguajesdeprogramacion.net/wp-content/uploads/2022/09/lenguajes-de-programacion-logo.png',
        profession: 'Ilustrador',
        subCategorias: ['UX Design', 'User Experience'],
        empresa: 'Tech desing',
        lugar: 'Barranquilla',
        salario: '30M COP',
        vacantes: 4,
        publicacion: '7 days ago',
    },
    {
        index: 6,
        image: 'https://e7.pngegg.com/pngimages/225/716/png-clipart-computer-icons-computer-programming-logo-bing-search-engine-people-angle-text.png',
        profession: 'Diseñador Grafico',
        subCategorias: ['Design',],
        empresa: 'Tech desing',
        lugar: 'Barranquilla',
        salario: '5M - 7M COP',
        vacantes: 2,
        publicacion: '9 days ago',
    },
    {
        index: 7,
        image: 'https://www.vectorizando.com/wp-content/uploads/2021/05/Lenguaje-de-programacion-C-64ca4748.svg',
        profession: 'Ilustrador',
        subCategorias: ['UX Design', 'User Experience'],
        empresa: 'Tech desing',
        lugar: 'Barranquilla',
        salario: '7M COP',
        vacantes: 6,
        publicacion: '11 days ago',
    },

];